### ISSUE TITLE
Замечания 1

### ISSUE THREAD

**Issue by katsvm** [grishinak/lab1_GrishinaK_23B18#1]
1. Функция вычисления экспоненты exp(x) по стандарту находится в заголовочном файле cmath. Подключите его корректно.
2. Поверните исходное изображение в обе стороны.

**Comment by grishinak** [comment]
Спасибо за ваши замечания, откорректировала файл main.cpp. 

Теперь изображение поворачивается в обе стороны, и фильтр Гаусса применяется именно к повернутому изображению. 
(к тому же изменила структуру заголовков bmp, что немного систематизирует работу с файлами такого формата).


> 1. Функция вычисления экспоненты exp(x) по стандарту находится в заголовочном файле cmath. Подключите его корректно.
> 2. Поверните исходное изображение в обе стороны.

**Comment by katsvm** [comment]
Всё выглядит хорошо. Стоит немного поработать над сокращение использования памяти: Вы сняли с себя заботу об освобождении пямяти с помощью std::vector'ов, но заплатили за это перерасходом памяти.
